// 12 classic nursery rhymes for sing-along mode
export const NURSERY_RHYMES = [
  {
    id: 'twinkle',
    title: 'Twinkle Twinkle Little Star',
    emoji: '⭐',
    lines: [
      'Twinkle twinkle little star',
      'How I wonder what you are',
      'Up above the world so high',
      'Like a diamond in the sky',
      'Twinkle twinkle little star',
      'How I wonder what you are',
    ],
  },
  {
    id: 'baa-baa',
    title: 'Baa Baa Black Sheep',
    emoji: '🐑',
    lines: [
      'Baa baa black sheep have you any wool',
      'Yes sir yes sir three bags full',
      'One for the master and one for the dame',
      'And one for the little boy who lives down the lane',
    ],
  },
  {
    id: 'old-macdonald',
    title: 'Old MacDonald Had a Farm',
    emoji: '🐄',
    lines: [
      'Old MacDonald had a farm E I E I O',
      'And on his farm he had a cow E I E I O',
      'With a moo moo here and a moo moo there',
      'Here a moo there a moo everywhere a moo moo',
      'Old MacDonald had a farm E I E I O',
    ],
  },
  {
    id: 'wheels',
    title: 'Wheels on the Bus',
    emoji: '🚌',
    lines: [
      'The wheels on the bus go round and round',
      'Round and round round and round',
      'The wheels on the bus go round and round',
      'All through the town',
      'The doors on the bus go open and shut',
      'Open and shut open and shut',
      'The doors on the bus go open and shut',
      'All through the town',
    ],
  },
  {
    id: 'row-row',
    title: 'Row Row Row Your Boat',
    emoji: '🚣',
    lines: [
      'Row row row your boat',
      'Gently down the stream',
      'Merrily merrily merrily merrily',
      'Life is but a dream',
    ],
  },
  {
    id: 'itsy-bitsy',
    title: 'Itsy Bitsy Spider',
    emoji: '🕷️',
    lines: [
      'The itsy bitsy spider went up the water spout',
      'Down came the rain and washed the spider out',
      'Out came the sun and dried up all the rain',
      'And the itsy bitsy spider went up the spout again',
    ],
  },
  {
    id: 'jack-and-jill',
    title: 'Jack and Jill',
    emoji: '⛰️',
    lines: [
      'Jack and Jill went up the hill',
      'To fetch a pail of water',
      'Jack fell down and broke his crown',
      'And Jill came tumbling after',
    ],
  },
  {
    id: 'humpty',
    title: 'Humpty Dumpty',
    emoji: '🥚',
    lines: [
      'Humpty Dumpty sat on a wall',
      'Humpty Dumpty had a great fall',
      'All the king\'s horses and all the king\'s men',
      'Couldn\'t put Humpty together again',
    ],
  },
  {
    id: 'mary-lamb',
    title: 'Mary Had a Little Lamb',
    emoji: '🐏',
    lines: [
      'Mary had a little lamb',
      'Its fleece was white as snow',
      'And everywhere that Mary went',
      'The lamb was sure to go',
      'It followed her to school one day',
      'Which was against the rule',
      'It made the children laugh and play',
      'To see a lamb at school',
    ],
  },
  {
    id: 'head-shoulders',
    title: 'Head Shoulders Knees and Toes',
    emoji: '🙆',
    lines: [
      'Head shoulders knees and toes knees and toes',
      'Head shoulders knees and toes knees and toes',
      'And eyes and ears and mouth and nose',
      'Head shoulders knees and toes knees and toes',
    ],
  },
  {
    id: 'if-youre-happy',
    title: "If You're Happy and You Know It",
    emoji: '😄',
    lines: [
      "If you're happy and you know it clap your hands",
      "If you're happy and you know it clap your hands",
      "If you're happy and you know it and you really want to show it",
      "If you're happy and you know it clap your hands",
    ],
  },
  {
    id: 'abc',
    title: 'The Alphabet Song',
    emoji: '🔤',
    lines: [
      'A B C D E F G',
      'H I J K L M N O P',
      'Q R S T U and V',
      'W X Y and Z',
      'Now I know my ABCs',
      'Next time won\'t you sing with me',
    ],
  },
]
